language: node_js
node_js:
- '8'
branchs:
  only:
  - master
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_3bfae2e07c70_key -iv $encrypted_3bfae2e07c70_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host ${SERVER_IP}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- scp -o stricthostkeychecking=no -r dist ${SERVER_NAME}@${SERVER_IP}:${VIEW_PATH}
addons:
  ssh_known_hosts:${SERVER_IP}