#指定node版本
language: node_js
node_js:
- '8'   

#指定只有检测到master分支有变动时才执行任务
branchs:
  only:
  - master  

# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

install:
- echo  $RSYNCPWD > rsyncd.passwd 
- chmod 600 rsyncd.passwd
- npm install
script:
- npm run build

after_success:
- rsync --delete --password-file=./rsyncd.passwd -r ./dist ${SERVER_NAME}@${SERVER_IP}::view